(cl:defpackage softarq_msgs-msg
  (:use )
  (:export
   "<POINT>"
   "POINT"
   "<SEQUENCEACTION>"
   "SEQUENCEACTION"
   "<SEQUENCEACTIONFEEDBACK>"
   "SEQUENCEACTIONFEEDBACK"
   "<SEQUENCEACTIONGOAL>"
   "SEQUENCEACTIONGOAL"
   "<SEQUENCEACTIONRESULT>"
   "SEQUENCEACTIONRESULT"
   "<SEQUENCEFEEDBACK>"
   "SEQUENCEFEEDBACK"
   "<SEQUENCEGOAL>"
   "SEQUENCEGOAL"
   "<SEQUENCERESULT>"
   "SEQUENCERESULT"
  ))

