; Auto-generated. Do not edit!


(cl:in-package softarq_msgs-msg)


;//! \htmlinclude SequenceFeedback.msg.html

(cl:defclass <SequenceFeedback> (roslisp-msg-protocol:ros-message)
  ((current
    :reader current
    :initarg :current
    :type cl:integer
    :initform 0))
)

(cl:defclass SequenceFeedback (<SequenceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SequenceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SequenceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name softarq_msgs-msg:<SequenceFeedback> is deprecated: use softarq_msgs-msg:SequenceFeedback instead.")))

(cl:ensure-generic-function 'current-val :lambda-list '(m))
(cl:defmethod current-val ((m <SequenceFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader softarq_msgs-msg:current-val is deprecated.  Use softarq_msgs-msg:current instead.")
  (current m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SequenceFeedback>) ostream)
  "Serializes a message object of type '<SequenceFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SequenceFeedback>) istream)
  "Deserializes a message object of type '<SequenceFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SequenceFeedback>)))
  "Returns string type for a message object of type '<SequenceFeedback>"
  "softarq_msgs/SequenceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SequenceFeedback)))
  "Returns string type for a message object of type 'SequenceFeedback"
  "softarq_msgs/SequenceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SequenceFeedback>)))
  "Returns md5sum for a message object of type '<SequenceFeedback>"
  "0b6da3dca7a4642ded212e4b180c47f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SequenceFeedback)))
  "Returns md5sum for a message object of type 'SequenceFeedback"
  "0b6da3dca7a4642ded212e4b180c47f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SequenceFeedback>)))
  "Returns full string definition for message of type '<SequenceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 current~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SequenceFeedback)))
  "Returns full string definition for message of type 'SequenceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 current~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SequenceFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SequenceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SequenceFeedback
    (cl:cons ':current (current msg))
))
