; Auto-generated. Do not edit!


(cl:in-package softarq_msgs-msg)


;//! \htmlinclude SequenceResult.msg.html

(cl:defclass <SequenceResult> (roslisp-msg-protocol:ros-message)
  ((last
    :reader last
    :initarg :last
    :type cl:integer
    :initform 0))
)

(cl:defclass SequenceResult (<SequenceResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SequenceResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SequenceResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name softarq_msgs-msg:<SequenceResult> is deprecated: use softarq_msgs-msg:SequenceResult instead.")))

(cl:ensure-generic-function 'last-val :lambda-list '(m))
(cl:defmethod last-val ((m <SequenceResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader softarq_msgs-msg:last-val is deprecated.  Use softarq_msgs-msg:last instead.")
  (last m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SequenceResult>) ostream)
  "Serializes a message object of type '<SequenceResult>"
  (cl:let* ((signed (cl:slot-value msg 'last)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SequenceResult>) istream)
  "Deserializes a message object of type '<SequenceResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'last) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SequenceResult>)))
  "Returns string type for a message object of type '<SequenceResult>"
  "softarq_msgs/SequenceResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SequenceResult)))
  "Returns string type for a message object of type 'SequenceResult"
  "softarq_msgs/SequenceResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SequenceResult>)))
  "Returns md5sum for a message object of type '<SequenceResult>"
  "5c5e0984025368e59f177a5859d58685")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SequenceResult)))
  "Returns md5sum for a message object of type 'SequenceResult"
  "5c5e0984025368e59f177a5859d58685")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SequenceResult>)))
  "Returns full string definition for message of type '<SequenceResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 last~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SequenceResult)))
  "Returns full string definition for message of type 'SequenceResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 last~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SequenceResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SequenceResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SequenceResult
    (cl:cons ':last (last msg))
))
