// Auto-generated. Do not edit!

// (in-package softarq_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SequenceGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.end_limit = null;
    }
    else {
      if (initObj.hasOwnProperty('end_limit')) {
        this.end_limit = initObj.end_limit
      }
      else {
        this.end_limit = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SequenceGoal
    // Serialize message field [end_limit]
    bufferOffset = _serializer.int64(obj.end_limit, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SequenceGoal
    let len;
    let data = new SequenceGoal(null);
    // Deserialize message field [end_limit]
    data.end_limit = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'softarq_msgs/SequenceGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1aab682b33bb2871b73e2f2a1b69674f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int64 end_limit
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SequenceGoal(null);
    if (msg.end_limit !== undefined) {
      resolved.end_limit = msg.end_limit;
    }
    else {
      resolved.end_limit = 0
    }

    return resolved;
    }
};

module.exports = SequenceGoal;
