// Auto-generated. Do not edit!

// (in-package softarq_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SequenceResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.last = null;
    }
    else {
      if (initObj.hasOwnProperty('last')) {
        this.last = initObj.last
      }
      else {
        this.last = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SequenceResult
    // Serialize message field [last]
    bufferOffset = _serializer.int64(obj.last, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SequenceResult
    let len;
    let data = new SequenceResult(null);
    // Deserialize message field [last]
    data.last = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'softarq_msgs/SequenceResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5c5e0984025368e59f177a5859d58685';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int64 last
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SequenceResult(null);
    if (msg.last !== undefined) {
      resolved.last = msg.last;
    }
    else {
      resolved.last = 0
    }

    return resolved;
    }
};

module.exports = SequenceResult;
