// Generated by gencpp from file softarq_msgs/DistanceResponse.msg
// DO NOT EDIT!


#ifndef SOFTARQ_MSGS_MESSAGE_DISTANCERESPONSE_H
#define SOFTARQ_MSGS_MESSAGE_DISTANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace softarq_msgs
{
template <class ContainerAllocator>
struct DistanceResponse_
{
  typedef DistanceResponse_<ContainerAllocator> Type;

  DistanceResponse_()
    : distance(0.0)  {
    }
  DistanceResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::softarq_msgs::DistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::softarq_msgs::DistanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceResponse_

typedef ::softarq_msgs::DistanceResponse_<std::allocator<void> > DistanceResponse;

typedef boost::shared_ptr< ::softarq_msgs::DistanceResponse > DistanceResponsePtr;
typedef boost::shared_ptr< ::softarq_msgs::DistanceResponse const> DistanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::softarq_msgs::DistanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::softarq_msgs::DistanceResponse_<ContainerAllocator1> & lhs, const ::softarq_msgs::DistanceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::softarq_msgs::DistanceResponse_<ContainerAllocator1> & lhs, const ::softarq_msgs::DistanceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace softarq_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::softarq_msgs::DistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softarq_msgs::DistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softarq_msgs::DistanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::softarq_msgs::DistanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "softarq_msgs/DistanceResponse";
  }

  static const char* value(const ::softarq_msgs::DistanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n"
"\n"
;
  }

  static const char* value(const ::softarq_msgs::DistanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::softarq_msgs::DistanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::softarq_msgs::DistanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOFTARQ_MSGS_MESSAGE_DISTANCERESPONSE_H
