// Generated by gencpp from file softarq_msgs/DistanceRequest.msg
// DO NOT EDIT!


#ifndef SOFTARQ_MSGS_MESSAGE_DISTANCEREQUEST_H
#define SOFTARQ_MSGS_MESSAGE_DISTANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <softarq_msgs/Point.h>
#include <softarq_msgs/Point.h>

namespace softarq_msgs
{
template <class ContainerAllocator>
struct DistanceRequest_
{
  typedef DistanceRequest_<ContainerAllocator> Type;

  DistanceRequest_()
    : a()
    , b()  {
    }
  DistanceRequest_(const ContainerAllocator& _alloc)
    : a(_alloc)
    , b(_alloc)  {
  (void)_alloc;
    }



   typedef  ::softarq_msgs::Point_<ContainerAllocator>  _a_type;
  _a_type a;

   typedef  ::softarq_msgs::Point_<ContainerAllocator>  _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::softarq_msgs::DistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::softarq_msgs::DistanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceRequest_

typedef ::softarq_msgs::DistanceRequest_<std::allocator<void> > DistanceRequest;

typedef boost::shared_ptr< ::softarq_msgs::DistanceRequest > DistanceRequestPtr;
typedef boost::shared_ptr< ::softarq_msgs::DistanceRequest const> DistanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::softarq_msgs::DistanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::softarq_msgs::DistanceRequest_<ContainerAllocator1> & lhs, const ::softarq_msgs::DistanceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::softarq_msgs::DistanceRequest_<ContainerAllocator1> & lhs, const ::softarq_msgs::DistanceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace softarq_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::softarq_msgs::DistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softarq_msgs::DistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softarq_msgs::DistanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0e70773e6ac30080ea63ef0547050aa";
  }

  static const char* value(const ::softarq_msgs::DistanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0e70773e6ac3008ULL;
  static const uint64_t static_value2 = 0x0ea63ef0547050aaULL;
};

template<class ContainerAllocator>
struct DataType< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "softarq_msgs/DistanceRequest";
  }

  static const char* value(const ::softarq_msgs::DistanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "softarq_msgs/Point a\n"
"softarq_msgs/Point b\n"
"\n"
"================================================================================\n"
"MSG: softarq_msgs/Point\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::softarq_msgs::DistanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::softarq_msgs::DistanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::softarq_msgs::DistanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    s << std::endl;
    Printer< ::softarq_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    s << std::endl;
    Printer< ::softarq_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOFTARQ_MSGS_MESSAGE_DISTANCEREQUEST_H
