// Generated by gencpp from file softarq_msgs/Distance.msg
// DO NOT EDIT!


#ifndef SOFTARQ_MSGS_MESSAGE_DISTANCE_H
#define SOFTARQ_MSGS_MESSAGE_DISTANCE_H

#include <ros/service_traits.h>


#include <softarq_msgs/DistanceRequest.h>
#include <softarq_msgs/DistanceResponse.h>


namespace softarq_msgs
{

struct Distance
{

typedef DistanceRequest Request;
typedef DistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Distance
} // namespace softarq_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::softarq_msgs::Distance > {
  static const char* value()
  {
    return "5ddefc5ca548808c4fec4ec87cfc211a";
  }

  static const char* value(const ::softarq_msgs::Distance&) { return value(); }
};

template<>
struct DataType< ::softarq_msgs::Distance > {
  static const char* value()
  {
    return "softarq_msgs/Distance";
  }

  static const char* value(const ::softarq_msgs::Distance&) { return value(); }
};


// service_traits::MD5Sum< ::softarq_msgs::DistanceRequest> should match
// service_traits::MD5Sum< ::softarq_msgs::Distance >
template<>
struct MD5Sum< ::softarq_msgs::DistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::softarq_msgs::Distance >::value();
  }
  static const char* value(const ::softarq_msgs::DistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::softarq_msgs::DistanceRequest> should match
// service_traits::DataType< ::softarq_msgs::Distance >
template<>
struct DataType< ::softarq_msgs::DistanceRequest>
{
  static const char* value()
  {
    return DataType< ::softarq_msgs::Distance >::value();
  }
  static const char* value(const ::softarq_msgs::DistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::softarq_msgs::DistanceResponse> should match
// service_traits::MD5Sum< ::softarq_msgs::Distance >
template<>
struct MD5Sum< ::softarq_msgs::DistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::softarq_msgs::Distance >::value();
  }
  static const char* value(const ::softarq_msgs::DistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::softarq_msgs::DistanceResponse> should match
// service_traits::DataType< ::softarq_msgs::Distance >
template<>
struct DataType< ::softarq_msgs::DistanceResponse>
{
  static const char* value()
  {
    return DataType< ::softarq_msgs::Distance >::value();
  }
  static const char* value(const ::softarq_msgs::DistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SOFTARQ_MSGS_MESSAGE_DISTANCE_H
