// Generated by gencpp from file softarq_msgs/SequenceGoal.msg
// DO NOT EDIT!


#ifndef SOFTARQ_MSGS_MESSAGE_SEQUENCEGOAL_H
#define SOFTARQ_MSGS_MESSAGE_SEQUENCEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace softarq_msgs
{
template <class ContainerAllocator>
struct SequenceGoal_
{
  typedef SequenceGoal_<ContainerAllocator> Type;

  SequenceGoal_()
    : end_limit(0)  {
    }
  SequenceGoal_(const ContainerAllocator& _alloc)
    : end_limit(0)  {
  (void)_alloc;
    }



   typedef int64_t _end_limit_type;
  _end_limit_type end_limit;





  typedef boost::shared_ptr< ::softarq_msgs::SequenceGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::softarq_msgs::SequenceGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SequenceGoal_

typedef ::softarq_msgs::SequenceGoal_<std::allocator<void> > SequenceGoal;

typedef boost::shared_ptr< ::softarq_msgs::SequenceGoal > SequenceGoalPtr;
typedef boost::shared_ptr< ::softarq_msgs::SequenceGoal const> SequenceGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::softarq_msgs::SequenceGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::softarq_msgs::SequenceGoal_<ContainerAllocator1> & lhs, const ::softarq_msgs::SequenceGoal_<ContainerAllocator2> & rhs)
{
  return lhs.end_limit == rhs.end_limit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::softarq_msgs::SequenceGoal_<ContainerAllocator1> & lhs, const ::softarq_msgs::SequenceGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace softarq_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::softarq_msgs::SequenceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softarq_msgs::SequenceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softarq_msgs::SequenceGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1aab682b33bb2871b73e2f2a1b69674f";
  }

  static const char* value(const ::softarq_msgs::SequenceGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1aab682b33bb2871ULL;
  static const uint64_t static_value2 = 0xb73e2f2a1b69674fULL;
};

template<class ContainerAllocator>
struct DataType< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "softarq_msgs/SequenceGoal";
  }

  static const char* value(const ::softarq_msgs::SequenceGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int64 end_limit\n"
;
  }

  static const char* value(const ::softarq_msgs::SequenceGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.end_limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SequenceGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::softarq_msgs::SequenceGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::softarq_msgs::SequenceGoal_<ContainerAllocator>& v)
  {
    s << indent << "end_limit: ";
    Printer<int64_t>::stream(s, indent + "  ", v.end_limit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOFTARQ_MSGS_MESSAGE_SEQUENCEGOAL_H
