// Generated by gencpp from file softarq_msgs/SequenceResult.msg
// DO NOT EDIT!


#ifndef SOFTARQ_MSGS_MESSAGE_SEQUENCERESULT_H
#define SOFTARQ_MSGS_MESSAGE_SEQUENCERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace softarq_msgs
{
template <class ContainerAllocator>
struct SequenceResult_
{
  typedef SequenceResult_<ContainerAllocator> Type;

  SequenceResult_()
    : last(0)  {
    }
  SequenceResult_(const ContainerAllocator& _alloc)
    : last(0)  {
  (void)_alloc;
    }



   typedef int64_t _last_type;
  _last_type last;





  typedef boost::shared_ptr< ::softarq_msgs::SequenceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::softarq_msgs::SequenceResult_<ContainerAllocator> const> ConstPtr;

}; // struct SequenceResult_

typedef ::softarq_msgs::SequenceResult_<std::allocator<void> > SequenceResult;

typedef boost::shared_ptr< ::softarq_msgs::SequenceResult > SequenceResultPtr;
typedef boost::shared_ptr< ::softarq_msgs::SequenceResult const> SequenceResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::softarq_msgs::SequenceResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::softarq_msgs::SequenceResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::softarq_msgs::SequenceResult_<ContainerAllocator1> & lhs, const ::softarq_msgs::SequenceResult_<ContainerAllocator2> & rhs)
{
  return lhs.last == rhs.last;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::softarq_msgs::SequenceResult_<ContainerAllocator1> & lhs, const ::softarq_msgs::SequenceResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace softarq_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::softarq_msgs::SequenceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::softarq_msgs::SequenceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softarq_msgs::SequenceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::softarq_msgs::SequenceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softarq_msgs::SequenceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::softarq_msgs::SequenceResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::softarq_msgs::SequenceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c5e0984025368e59f177a5859d58685";
  }

  static const char* value(const ::softarq_msgs::SequenceResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c5e0984025368e5ULL;
  static const uint64_t static_value2 = 0x9f177a5859d58685ULL;
};

template<class ContainerAllocator>
struct DataType< ::softarq_msgs::SequenceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "softarq_msgs/SequenceResult";
  }

  static const char* value(const ::softarq_msgs::SequenceResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::softarq_msgs::SequenceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int64 last\n"
;
  }

  static const char* value(const ::softarq_msgs::SequenceResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::softarq_msgs::SequenceResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.last);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SequenceResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::softarq_msgs::SequenceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::softarq_msgs::SequenceResult_<ContainerAllocator>& v)
  {
    s << indent << "last: ";
    Printer<int64_t>::stream(s, indent + "  ", v.last);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOFTARQ_MSGS_MESSAGE_SEQUENCERESULT_H
